version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  
  producer:
    build: .
    container_name: producer
    command: python producer.py
    depends_on:
      - redis
  
  consumer:
    build: .
    container_name: consumer
    command: python consumer.py
    depends_on:
      - redis

